server:
  port: 8782
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8781/eureka/
    fetch-registry: false                           #是否将自己注册到Eureka Server 默认为true
    register-with-eureka: true                     #是否从Eureka Server查询注册信息
  instance:
    hostname: eureka-slave2
  server:
    enable-self-preservation: false
