server:
  port: 8082
spring:
  application:
    name: grpc-spring-cloud-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8781/eureka/,http://localhost:8782/eureka/
  instance:
    instance-id: grpc-consumer
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
# actuator management
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
# actuator info
info:
  app:
    encoding:UTF-8
    java.source:1.8
    java.traget:1.8
    name:grpc-spring-cloud-consumer